---
abstract: 'Logging to date/time stamped files'
author:
  - 'Eric Cholet <cholet@logilune.com>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Dispatch-File-Stamped
provides:
  Log::Dispatch::File::Stamped:
    file: lib/Log/Dispatch/File/Stamped.pm
    version: 0.10
requires:
  Log::Dispatch: 0
  Log::Dispatch::File: 0
  Test::More: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.10
