---
abstract: 'Logging to date/time stamped files'
author:
  - 'Eric Cholet <cholet@logilune.com>'
  - 'Karen Etheridge <ether@cpan.org'
configure_requires:
  Module::Build: 0.36
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Dispatch-File-Stamped
provides:
  Log::Dispatch::File::Stamped:
    file: lib/Log/Dispatch/File/Stamped.pm
    version: 0.10_010
requires:
  Log::Dispatch: 0
  Log::Dispatch::File: 2.38
  Test::More: 0.88
  Test::TempDir: 0
  Path::Tiny: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.10_010
x_contributors:
  - 'Eric Cholet <cholet@logilune.com>'
  - 'Karen Etheridge <ether@cpan.org'
